version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: planmebackend_production_django
    env_file:
      - ./.envs/.production/.django
    command: /start
