#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Collecting static files..."
python /app/manage.py collectstatic --noinput

echo "Starting Gunicorn..."
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:$PORT --chdir=/app
