# Generated by Django 4.2.6 on 2023-10-19 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subtask",
            options={"ordering": ["id"], "verbose_name": "SubTask", "verbose_name_plural": "SubTasks"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["due_date"], "verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["id"], "verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.RemoveField(
            model_name="subtask",
            name="subtask_id",
        ),
        migrations.RemoveField(
            model_name="task",
            name="task_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
        migrations.AddField(
            model_name="subtask",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="task",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="user",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="DataVisualization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="data_visualization", to="app.task"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="dashboard", to="app.user"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
