# Generated by Django 4.2.6 on 2023-10-21 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="bullet_text",
        ),
    ]
