# Generated by Django 4.2.7 on 2023-11-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_subtask_status_alter_subtask_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
