# Generated by Django 4.2.7 on 2023-11-18 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('course', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DeletedTask',
                'verbose_name_plural': 'DeletedTasks',
                'ordering': ['id'],
            },
        ),
    ]
