name: CI

on:
  pull_request:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Build the Stack
        env:
          DOCKER_BUILDKIT: 1
        run: docker-compose -f local.yml build
    outputs:
      image-hash: ${{ steps.build.outputs.digest }}

  migrate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run DB Migrations
        run: docker-compose -f local.yml run --rm django python manage.py migrate

  test:
    needs: migrate
    runs-on: ubuntu-latest
    steps:
      - name: Run API Tests
        run: docker-compose -f local.yml run --rm django pytest -vv

  teardown:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Tear down the Stack
        run: docker-compose -f local.yml down
